In [266]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

data = pd.read_csv('181~ 360.csv', encoding='utf-8', header=None, names=['names', 'main_category', 'ratings', 'keywords'])

In [267]:
data['keywords'][data['keywords'].isna()] = ''    # NaN값을 빈 문자열로 대체

def preprocess(string):
    
# '/', '&' 같은 문자 제거
# '장소', '및', '전문', '시설' 등과 같은 수식어 제거    
# 필요한경우 띄어쓰기 제거 (e.g. 인근 지역 -> 인근지역)

    # 공통
    
    string = string.replace(' /', '')
    string = string.replace(' &', '')
    string = string.replace(' 및', '')
    string = string.replace('아쿠아리움', '수족관') # 중복제거를 위해 아쿠아리움을 수족관으로 통일
    
    # main_category
    
    string = string.replace('보트 투어', '보트투어')
    string = string.replace('수상 스포츠', '수상스포츠')
    string = string.replace('즐길 거리', '즐길거리')
    string = string.replace('야외 활동', '야외활동')
    string = string.replace('여행자 자료', '여행자자료')

    # keywords

    string = string.replace('쇼핑몰', '쇼핑')
    string = string.replace('전문 박물관', '전문박물관 박물관')
    string = string.replace('어린이 박물관', '어린이박물관 박물관')
    string = string.replace('자연사 박물관', '자연사박물관 박물관')
    string = string.replace('군사 박물관', '군사박물관 박물관')
    string = string.replace(' 장소', '') # 종교적인 장소, 교육적인 장소
    string = string.replace('인근 지역', '인근지역')
    string = string.replace('경관이 좋은 산책로', '경관좋은산책로')
    string = string.replace('유서 깊은 산책로', '유서깊은산책로')
    string = string.replace('공공기관 건물', '공공기관건물')
    string = string.replace('고대 유적', '고대유적')
    string = string.replace('군사 기지', '군사기지')
    string = string.replace('자동차 경주장', '자동차경주장')
    string = string.replace('절경 드라이브 코스', '절경드라이브코스')
    string = string.replace('하이킹 트레일', '하이킹트레일')
    string = string.replace('야생동물 서식지', '야생동물서식지')
    string = string.replace('엔터테인먼트 센터', '엔터테인먼트센터')
    string = string.replace('도자기 스튜디오', '도자기스튜디오')
    string = string.replace('방 탈출 게임', '방탈출게임 게임')
    string = string.replace('기타 놀이', '게임') 
    string = string.replace('미니 골프', '미니골프')
    string = string.replace('물건 찾기 게임', '물건찾기게임 게임')
    string = string.replace('테마 파크', '테마파크')
    string = string.replace('대중교통 시스템', '대중교통시스템')
    
    return string

data['main_category'] = data['main_category'].apply(preprocess)
data['keywords'] = data['keywords'].apply(preprocess)





def leave_space(string):
    return ' ' + string

data['keywords_aggregated'] = data['main_category'] + data['keywords'].apply(leave_space)

data = data.drop(['main_category', 'keywords'], axis=1)

data = data.rename(columns = {'keywords_aggregated' : 'keywords'})


# 중복되는 단어 처리

def duplicates_handle(string):
    string_list = string.split(' ')
    
    tmp = []
    
    to_del = []
    
    for val in string_list:
        if string_list.count(val)!=1:
            to_del.append(val)
            tmp.append(val)

    for val in to_del:
        string = string.replace(val, '')
    
    tmp_str = ' '
    
    for val in list(set(tmp)):
        tmp_str = tmp_str + val
    
    string = string + tmp_str
    
    return string


words = ['스포츠', '게임', '박물관', '공원', '쇼핑']

for word in words:
    data['keywords'] = data['keywords'].apply(duplicates_handle)

                   
data

            names  ratings                  keywords
0     이천 세계 도자 센터     4.75               전문  박물관
1    신세계 백화점 센텀시티     4.48               쇼핑 백화점
2             미륵산     4.66       자연 공원 산 하이킹트레일
3         성남 아트센터     4.62            즐길거리  랜드마크
4             관촉사     4.83        랜드마크 신성한 종교적인
..            ...      ...                       ...
175          완산공원     4.65               자연   공원
176         용눈이오름     4.87             자연 공원 화산
177         명동 성당     4.64  랜드마크 신성한 종교적인 교회 성당
178        익산미륵사지     4.46        랜드마크 신성한 종교적인
179           수도사     4.50   랜드마크 역사적인 신성한 종교적인

[180 rows x 3 columns]

In [1]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
count_vector = CountVectorizer(ngram_range=(1, 10))

In [3]:
c_vector_keywords = count_vector.fit_transform(data['keywords'])

NameError: name 'data' is not defined